
$.fn.isOnScreen=function(){var win=$(window);var viewport={top:win.scrollTop(),left:win.scrollLeft()};viewport.right=viewport.left+win.width();viewport.bottom=viewport.top+win.height();var bounds=this.offset();bounds.right=bounds.left+this.outerWidth();bounds.bottom=bounds.top+this.outerHeight();return(!(viewport.right<bounds.left||viewport.left>bounds.right||viewport.bottom<bounds.top||viewport.top>bounds.bottom));};var BLOCKED_ELEMENT=false;var BLOCK_UI_CALLED=false;function showCustomAlert(text){var uniAlert=window['showUniAlert'];if($.isFunction(uniAlert)){uniAlert(text);}else{alert(text);}}
$(window).bind('pageshow',function(){if(!BLOCK_UI_CALLED)unblockUI();});$(document).ready(function(){$.blockUI.defaults.css={};$.blockUI.defaults.overlayCSS={};$('form :input').change(function(){var $inp=$(this);resetError($inp);$inp.closest('form').data('changed',true);return true;});$(document).ajaxError(function(event,jqxhr,settings,thrownError){if(settings.url&&settings.url.indexOf('://127.0.0.1')>0)return;if(settings.suppressErrors)return;unblockUI(function(){processError(jqxhr,thrownError);});});function processError(XMLHttpRequest,errorThrown){if(XMLHttpRequest.responseText){try{var result=$.parseJSON(XMLHttpRequest.responseText);if(result.STATUS){var status=result.STATUS;if(status==401){if(window.form_unauthorized){window.form_unauthorized(result.ERROR);}else{window.location.reload(true);}
return;}else if(status>=300&&status<400){var location=result.HEADERS?result.HEADERS['Location']:false;if(location){window.location.href=location;return;}}}
if(result.ERRORS){if(window.form_errors){window.form_errors(result.ERRORS);}else{showErrors(result.ERRORS);}
return;}
if(result.ERROR){showCustomAlert(result.ERROR);return;}}catch(e){}}
showCustomAlert('Ошибка получения данных');}
$('form[autocomplete="off"]').append('<input type="text" class="inp-std" style="display:none" id="PreventChromeAutocomplete" name="PreventChromeAutocomplete" autocomplete="no"/>');$('form').not('.noajax').bind('reset',function(){return false;});$('#btn_reset').click(function(){if(!confirm('Вы уверены, что хотите очистить все введенные значения на форме?'))return;if(window.form_reset){window.form_reset();}else{window.location.reload(true);}});$('#btn_cancel').click(function(){if(window.URL_CANCEL){location.href=window.URL_CANCEL;}});$('form').not('.noajax').submit(function(){var form=this;var $form=$(form);var form_onsubmit=getEventHandler($form,'onsubmit');if(!form_onsubmit||form_onsubmit(form)){if($form.hasClass('noajax')){return true;}
var target=$form.attr('target');if(target&&target!='iframe'){return true;}
hideErrors();$('#pnl_result').hide();if(isMultipartFromData($form)&&!getFormData($form)){var $inpHtmlTag=$form.find('input[name="html"]');if(!$inpHtmlTag.length){$inpHtmlTag=$('<input type="hidden" name="html"/>');$form.append($inpHtmlTag);}
$inpHtmlTag.val('1');var iframeId='iframe';$form.attr('target',iframeId);var $iframe=$('iframe#'+iframeId);if(!$iframe.length){$iframe=$('<iframe id="'+iframeId+'" name="'+iframeId+'" src="about:blank"/>');$('body').append($iframe);$iframe.load(iframe_onload);}
$iframe.attr('data-form-id',$form.attr('id'));blockUI(null,form);return true;}else{submitAjax(form,true);return false;}}
return false;});if(window.form_init)window.form_init();$('#pnl_request').show();});function isMultipartFromData($form){var enctype=$form.attr('enctype');return enctype&&enctype.toLowerCase()=='multipart/form-data';}
function getFormData($form){try{return new FormData($form[0]);}catch(e){return false;}}
function getEventHandler($obj,eventName){if(!$obj||!$obj.length)return getFunctionByName('form_'+eventName);var handler=false;var id=$obj.attr('id');if(id)handler=getFunctionByName(id+'_'+eventName);if(!handler)handler=getFunctionByName($obj.prop("tagName").toLowerCase()+'_'+eventName);return handler;}
function getFunctionByName(functionName){var result=window[functionName];return $.isFunction(result)?result:false;}
function iframe_onload(){var $iframe=$(this);var content;try{content=$iframe.contents().find('body').html();}catch(e1){content='{"ERROR":"'+'Ошибка получения данных'+' (failed)"}';}
var result;try{result=$.parseJSON(content);}catch(e2){result={ERROR:'Ошибка получения данных'+' (parse error)'};}
var formId=$iframe.attr('data-form-id');var $form=$('#'+formId);processResult(result,$form);}
function processResult(result,$form){if(!result){processSuccess(result,$form);}else if(result.ERRORS){showErrors(result.ERRORS);unblockUI();}else if(result.ERROR){showCustomAlert(result.ERROR);unblockUI();}else{processSuccess(result,$form);}}
function processSuccess(result,$form){var form_onsuccess=getEventHandler($form,'onsuccess');if(form_onsuccess){if(!form_onsuccess(result)){resetCaptcha();unblockUI();}}else if(window.URL_OK){location.href=window.URL_OK;}else{resetCaptcha();unblockUI();}}
function blockUI(onBlock,element){BLOCK_UI_CALLED=true;if($.blockUI){if(element&&element.tagName=='FORM'){if($(element).hasClass('modal-form')){element=$(element).closest('.modal');}else{element=null;}}
BLOCKED_ELEMENT=element;if(!element){if($('.blockPage').is(':visible')){if(onBlock)onBlock();}else{$.blockUI({message:'Пожалуйста, подождите',onBlock:onBlock});}}else{$(element).block({message:'Пожалуйста, подождите',onBlock:onBlock});}}}
function unblockUI(onUnblock){if($.unblockUI){if(!BLOCKED_ELEMENT){if($('.blockPage').is(':visible')){$.unblockUI({onUnblock:onUnblock});}else{if(onUnblock)onUnblock();}}else{$(BLOCKED_ELEMENT).unblock({onUnblock:onUnblock});}}}
function ajax(params,doBlockUI){if(doBlockUI){blockUI(function(){ajax(params,false);});}else{$.ajax(params);}}
function submitAjax(form,doBlockUI,url){var $form=!form?$('#frm'):$(form);if(doBlockUI){var blockElement;if($form.hasClass('modal-form'))blockElement=$form[0];blockUI(function(){submitAjax($form[0],false,url);},blockElement);}else{if(!url)url=$form.attr('action');if(isMultipartFromData($form)){var formData=getFormData($form);formData.append('t',new Date().getTime());$.ajax({url:url,data:formData,type:'POST',contentType:false,processData:false,success:function(result){processSuccess(result,$form);},dataType:'json'});}else{$.ajax({type:$form.attr('method'),url:url,data:$form.serialize(),success:function(result){processSuccess(result,$form);},dataType:'json'});}}}
function submitForm(form){var $form=!form?$('#frm'):$(form);$form.submit();}
function hideErrors(){$('form .field-errors').hide();var $inpErr=$('form .input-error');$inpErr.filter('.error-title').removeAttr('title');$inpErr.removeClass('input-error');}
function resetCaptcha(){$('.captcha-field').each(function(){var $this=$(this);var $img=$this.find('img');var $token=$this.find('input[name=captchaToken]');$this.find('input[name=captcha]').val('');$.get('/static/captcha.bin?r='+(new Date()).getTime()).success(function(response){$img.attr('src','/static/captcha.bin?a='+response+'&version='+window['CAPTCHA_VERSION']);$token.val(response);}).error(function(){showCustomAlert('Ошибка при получении картинки. Нажмите "Обновить картинку с цифрами".');});});}
function showErrors(errors){hideErrors();var scrolled=false;$.each(errors,function(name,list){if(name==='captchaToken'){resetCaptcha();return true;}
var $inp=$('#'+name);if(!$inp.length)$inp=$(':input[name='+name+']');if(!$inp.length){showCustomAlert(getErrorsText(list));}else{if($inp.length>1){var $enabled=$inp.not(':disabled');if($enabled.length&&$enabled.length<$inp.length){$inp=$enabled;}}
if($inp.hasClass('error-title')){$inp.attr('title',getErrorsText(list));}else{var $errors=$('#errors_'+name);if(!$errors.length){var $fieldValue=$inp.closest('.field-value');$errors=$('<ul class="field-errors" id="errors_'+name+'"></ul>');$fieldValue.after($errors);}
var html='';$.each(list,function(i,err){if(!$inp.is(':checkbox')){html+='<li><label for="'+name+'">'+htmlEncode(err,true)+'</label></li>';}else{html+='<li>'+htmlEncode(err,true)+'</li>';}});$errors.html(html).show();if(!$errors.is(':visible')){showCustomAlert(getErrorsText(list));}}
if($inp.data('inpId')){$('#'+$inp.data('inpId')).addClass('input-error');}else if($inp.data('editor-id')){$('#'+$inp.data('editor-id')).addClass('input-error');}
$inp.not('input:radio').addClass('input-error');if(!scrolled){if($inp.is(':visible')){if(!$inp.isOnScreen())$inp[0].scrollIntoView(true);scrolled=true;}else if($errors.is(':visible')){if(!$errors.isOnScreen())$errors[0].scrollIntoView(true);scrolled=true;}}}});}
function getErrorsText(list){var text=[];$.each(list,function(i,err){if(text.length)text.push('\n');text.push(err);});return text.join('');}
function htmlEncode(s,lineBreaks){if(!s)return'';var result=s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');if(lineBreaks)result=result.replace(/\n/g,'<br>');return result;}
function unlockField($field){if(!$field.hasClass('field-locked'))return;$field.children('.field-caption').find('span').removeClass('hidden');var $fieldData=$field.children('.field-data');$fieldData.find('.field-text').hide();$fieldData.find('.field-value').show();$fieldData.find('.field-hint').show();$field.removeClass('field-locked');}
function lockField($fields){$fields.each(function(){var $field=$(this);if($field.hasClass('field-locked'))return;var $fieldData=$field.children('.field-data');var $fieldValue=$fieldData.find('.field-value');var val='';var found=false;var $inp=$fieldValue.find('.field-locked-value');if($inp.length){val=$inp.val();found=true;}
if(!found){$inp=$fieldValue.find('input[type=text]:visible');if($inp.length){var inp=$inp.get(0);if(inp.params&&inp.params.uni_set){val=$inp.uni_set('getText');}else{val=$inp.val();}
found=true;}}
if(!found){$inp=$fieldValue.find('select:visible');if($inp.length){found=true;val=$inp.children('option:selected').text();}}
if(!found){$inp=$fieldValue.find('input[type=radio]');if($inp.length){found=true;$inp=$inp.filter(':checked');if($inp.length){val=$inp.val();var $label=$fieldValue.find('label[for='+$inp.attr('id')+']');if($label.length)val=$label.text();}else{val='';}}}
if(found){var $fieldText=$fieldData.find('.field-text');if(!$fieldText.length){$fieldText=$('<div class="field-text"></div>');$fieldData.prepend($fieldText);}
$field.children('.field-caption').find('span').addClass('hidden');$fieldData.find('.field-hint').hide();$field.addClass('field-locked');$fieldValue.hide();if(val.length){$fieldText.text(val).show().removeClass('field-text-empty');}else{$fieldText.text('(пусто)').show().addClass('field-text-empty');}}});}
function unlockFields($pnl){$pnl.find('.lock-hide').show();$pnl.find('i.uni-hint-trigger').css('display','inline-block');$pnl.find('.form-field').each(function(){var $field=$(this);unlockField($field);});}
function lockFields($pnl){$pnl.find('.lock-hide').hide();$pnl.find('i.uni-hint-trigger').css('display','none');$pnl.find('.form-field').each(function(){var $field=$(this);lockField($field);});}
function setFieldValues(form,data,meta){var $form=$(form);if(!$form.length)$form=$(document);if(!meta){$.each(data,function(key,values){var $inp=$form.find('#'+key);if(!$inp.length)$inp=$form.find(':input[name='+key+']');if($inp.hasClass('fixed'))return true;if(!$.isArray(values))values=[values];$.each(values,function(index,value){if($inp.is(':radio')){$inp.removeAttr('checked');$inp.filter('[value="'+value+'"]').attr('checked','checked');}else if($inp.is(':checkbox')){if(value){$inp.attr('checked','checked');}else{$inp.removeAttr('checked');}}else{$inp.val(value);}});});}else{$.each(meta,function(key,value){var fieldName=value.name;var dataName=value.dataName;var type=value.type;var fieldValue=data[dataName];if(type=='DATE'&&fieldValue&&fieldValue.length>10)fieldValue=fieldValue.substr(0,10);if(type=='CURRENCY'&&typeof fieldValue=='number')fieldValue=fieldValue.toFixed(2);var $inp=$form.find('#'+fieldName);if(!$inp.length)$inp=$form.find(':input[name='+fieldName+']');if($inp.is(':radio')){$inp.removeAttr('checked');$inp.filter('[value="'+fieldValue+'"]').attr('checked','checked');}else if($inp.is(':checkbox')){if(fieldValue){$inp.attr('checked','checked');}else{$inp.removeAttr('checked');}}else if($inp.is(':input')){$inp.val(fieldValue);}else{$inp.text(fieldValue);}});}}
function resetError($inp){var name=$inp.attr('name');if(!name)name=$inp.attr('id');window.setTimeout(function(){$('#errors_'+name).hide();},200);if($inp.data('inpId')){$('#'+$inp.data('inpId')).removeClass('input-error');}else if($inp.data('editor-id')){$('#'+$inp.data('editor-id')).removeClass('input-error');}
$inp.removeClass('input-error');}
function i18n(text){return text;};