
$(document).ready(function(){$(window).resize(function(){var $container=$('#uniDialogContainer');if($container.is(':visible')){var maxWidth=$container.data('maxWidth');var maxHeight=$container.data('maxHeight');var currentWidth=$container.width();var currentHeight=$container.height();var windowWidth=Math.max($(window).width(),320);var windowHeight=$(window).height();if(!maxWidth||maxWidth<0)maxWidth=windowWidth;if(!maxHeight||maxHeight<0)maxHeight=windowHeight;var w=Math.min(Math.max(Math.min(maxWidth,windowWidth),400),windowWidth);var h=Math.min(Math.max(Math.min(maxHeight,windowHeight),100),windowHeight);if(currentWidth!=w||currentHeight!=h){var marginTop='';if($('#uniDialogContainer').css('margin-top')!='0px'){marginTop='-'+h/2+'px';}
$('#uniDialogContainer').css({'width':w+'px','height':h+'px','margin-left':'-'+w/2+'px','margin-top':marginTop});}}
return true;});});function showUniAlert(options,$input){if(window['RTKOMM_PAGE_STYLE']=='GU'&&(!$input||!$input.length)){alert(getAlertText(options));return;}
if(typeof options==='string'){options={text:options};}else if(!$.isPlainObject(options)){options={};}
if(!options.title)options.title='Уважаемый пользователь!';if(!options.text)options.text='';if(!options.html)options.html='<p>'+options.text.split('\n').join('</p><p>')+'</p>';if(!options.width)options.width=600;if(!options.height)options.height=200;window['UNI_ALERT']=options;showUniDialog('/static/alert.html',options.width,options.height,false,$input)
function getAlertText(options){if(typeof options==='string'){return options;}else if(!$.isPlainObject(options)){return'';}else if(options.text){return options.text;}else if(options.html){return $('<div></div>').html(options.html).text();}else{return'';}}}
function showUniConfirm(options,$input){if(typeof options==='string'){options={text:options};}else if(!$.isPlainObject(options)){options={};}
if(!options.title)options.title='Уважаемый пользователь!';if(!options.text)options.text='';if(!options.html)options.html='<p>'+options.text.split('\n').join('</p><p>')+'</p>';if(!options.width)options.width=600;if(!options.height)options.height=200;if(!options.buttons)options.buttons=[{caption:'ОК'}];window['UNI_CONFIRM']=options;showUniDialog('/static/confirm.html',options.width,options.height,false,$input)}
function setQueryParam(url,paramName,paramValue){url=removeQueryParam(url,paramName);return addQueryParam(url,paramName,paramValue);}
function getQueryHash(url){var pos=url.indexOf('#');return pos>=0?url.substr(pos):'';}
function removeQueryHash(url){var hash=getQueryHash(url);return url.substr(0,url.length-hash.length);}
function removeQueryParam(url,paramName){var pos1=url.indexOf('&'+paramName+'=');if(pos1<0){pos1=url.indexOf('?'+paramName+'=');if(pos1<0)return url;pos1++;}
var hash=getQueryHash(url);url=removeQueryHash(url);var pos2=url.indexOf('&',pos1+1);if(pos2<0){return url.substr(0,pos1)+hash;}else{return url.substr(0,pos1)+url.substr(pos2)+hash;}}
function getQueryParam(url,paramName){if(!paramName){paramName=url;url=location.href;}
var pos1=url.indexOf('&'+paramName+'=');if(pos1<0){pos1=url.indexOf('?'+paramName+'=');if(pos1<0)return'';}
pos1+=paramName.length+2;var pos2=url.indexOf('&',pos1);if(pos2<0){return url.substring(pos1);}else{return url.substring(pos1,pos2);}}
function addQueryParam(url,paramName,paramValue){if(url.indexOf('&'+paramName+'=')>=0||url.indexOf('?'+paramName+'=')>=0)return url;var hash=getQueryHash(url);url=removeQueryHash(url);url+=url.indexOf('?')>=0?'&':'?';url+=paramName+'='+encodeURIComponent(paramValue);return url+hash;}
function showUniDialog(url,width,height,overlayClose,$input){if($('#uniDialog').is(':visible'))return;if(window.RTKOMM_PAGE_STYLE=='GU'&&!$('body').hasClass('dialog')&&$input&&$input.length){showUniDialogInWidget(url,width,height,overlayClose,$input);return;}
var w=width;var h=height;if(!w||w<0)w=$(window).width();if(!h||h<0)h=$(window).height();var w=Math.max(Math.min(w,$(window).width()),400);var h=Math.max(Math.min(h,$(window).height()),300);$('#uniDialog').remove();var $uniDialog=$('<div class="uni-dialog" id="uniDialog">'+'<div class="uni-dialog-wrapper" id="uniDialogWrapper"></div>'+'<div class="uni-dialog-container" id="uniDialogContainer">'+'<div class="uni-dialog-data" id="uniDialogData">'+'<iframe class="uni-dialog-frame" id="uniDialogFrame" scrolling="no" frameBorder="0">'+'</div></div></div></div>');$('body').append($uniDialog);$('#uniDialogWrapper').click(function(){if($(this).data('overlayClose'))hideUniDialog();});overlayClose=!overlayClose?false:true;$('#uniDialogWrapper').data('overlayClose',overlayClose);$('#uniDialogContainer').css({'width':w+'px','height':h+'px','margin-left':'-'+w/2+'px','margin-top':'-'+h/2+'px','top':''}).data({'maxWidth':width,'maxHeight':height});if(window.APPLICATION_VERSION)url=setQueryParam(url,'aver',window.APPLICATION_VERSION);if(window.STATIC_VERSION)url=setQueryParam(url,'sver',window.STATIC_VERSION);if(window.RTKOMM_PAGE_STYLE)url=setQueryParam(url,'pageStyle',window.RTKOMM_PAGE_STYLE);if(window.APP_PATH)url=setQueryParam(url,'appPath',window.APP_PATH);var $iframe=$('#uniDialogFrame');$iframe.contents().find('body').html('');$iframe.on('load',function(){$iframe[0].contentWindow.focus();});$iframe.attr('src',url);$uniDialog.show();var overflow=$('body').css('overflow');$('body').attr('data-overflow',overflow).css('overflow','hidden');$(window).triggerHandler('resize');}
function showUniDialogInWidget(url,width,height,overlayClose,$input){if($('#uniDialog').is(':visible'))return;if(!width)width=780;if(!height)height=550;height+=150;width=Math.min(width,780);height=Math.min(height,700);var windowWidth=$(window).width();var windowHeight=$(window).height();var inputTop=$input.offset().top;var w=Math.max(Math.min(width,windowWidth),600);var h=Math.max(Math.min(height,windowHeight),500);var $uniDialog=$('#uniDialog');if(!$uniDialog.length){$uniDialog=$('<div class="uni-dialog" id="uniDialog">'+'<div class="uni-dialog-wrapper" id="uniDialogWrapper"></div>'+'<div class="uni-dialog-container" id="uniDialogContainer">'+'<div class="uni-dialog-data" id="uniDialogData">'+'<iframe class="uni-dialog-frame" id="uniDialogFrame" scrolling="no" frameBorder="0">'+'</div></div></div></div>');$('body').append($uniDialog);$('#uniDialogWrapper').click(function(){if($(this).data('overlayClose'))hideUniDialog();});}
overlayClose=!overlayClose?false:true;$('#uniDialogWrapper').data('overlayClose',overlayClose);var top=Math.min(inputTop-h/2,windowHeight-h);if(top<0)top=0;$('#uniDialogContainer').css({'width':w+'px','height':h+'px','margin-left':'-'+w/2+'px','margin-top':'0px','top':top+'px'}).data({'maxWidth':width,'maxHeight':height});if(window.APPLICATION_VERSION)url=setQueryParam(url,'aver',window.APPLICATION_VERSION);if(window.STATIC_VERSION)url=setQueryParam(url,'sver',window.STATIC_VERSION);if(window.RTKOMM_PAGE_STYLE)url=setQueryParam(url,'pageStyle',window.RTKOMM_PAGE_STYLE);if(window.APP_PATH)url=setQueryParam(url,'appPath',window.APP_PATH);var $iframe=$('#uniDialogFrame');$iframe.contents().find('body').html('');$iframe.load(function(){$iframe[0].contentWindow.focus();});$iframe.attr('src',url);$uniDialog.show();var overflow=$('body').css('overflow');$('body').attr('data-overflow',overflow).css('overflow','hidden');$(window).triggerHandler('resize');}
function hideUniDialog(){if($('#uniDialog').is(':visible')){window.setTimeout(function(){$('#uniDialog').hide();$('body').css('overflow',$('body').attr('data-overflow'));},10);return true;}else{return false;}}
function resizeUniDialog(width,height){if($('#uniDialog').is(':visible')){$('#uniDialogContainer').data({'maxWidth':width,'maxHeight':height});$(window).trigger('resize');}}
function closeUniDialog(){var parent=getParentWindow();if(!parent)return false;return parent.hideUniDialog();}
function getParentWindow(){if(window.opener&&window.opener!=window)return window.opener;if(window.parent&&window.parent!=window)return window.parent;return null;}
function getParentDocument(){var parent=getParentWindow();if(parent)return parent.document;return null;};